service: highcharts

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 512
  timeout: 10

functions:
  graph:
    handler: handler.graph
    events:
      - http:
          path: /
          method: ANY
          cors: true
