service: restcharts

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 512
  timeout: 10
  environment: ${file(serverless.env.yml):${self:provider.stage}}

functions:
  graph:
    handler: handler.graph
    events:
      - http:
          path: /
          method: ANY
          cors: true
