service: highcharts
frameworkVersion: ">=1.34.0 <2.0.0"

plugins:
  - serverless-offline
  - serverless-apigw-binary
  - serverless-apigwy-binary

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: us-east-1
  memorySize: 512
  timeout: 10

layers:
  phantomjs:
    path: bin

custom:
  apigwBinary:
    types:
      - 'image/png'

functions:
  graph:
    handler: handler.graph
    events:
      - http:
          path: /
          method: ANY
          contentHandling: CONVERT_TO_BINARY
          cors:
            origin: '*'
            maxAge: 86400
            allowCredentials: true
    layers:
      - {Ref: PhantomjsLambdaLayer}
